package app

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestComposePassesTreeAuditConfigurationToAPI(t *testing.T) {
	path := filepath.Join("..", "..", "compose.yaml")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	compose := string(content)
	want := []string{
		"AZURE_OPENAI_TREE_AUDIT_DEPLOYMENT: ${AZURE_OPENAI_TREE_AUDIT_DEPLOYMENT:-}",
		"AZURE_OPENAI_FINAL_TREE_REVIEW_DEPLOYMENT: ${AZURE_OPENAI_FINAL_TREE_REVIEW_DEPLOYMENT:-}",
		"TREE_AUDIT_ENABLED: ${TREE_AUDIT_ENABLED:-true}",
		"TREE_AUDIT_INTERVAL_VERSIONS: ${TREE_AUDIT_INTERVAL_VERSIONS:-3}",
		"TREE_AUDIT_INTERVAL_SECONDS: ${TREE_AUDIT_INTERVAL_SECONDS:-300}",
		"TREE_AUDIT_MIN_INTERVAL_SECONDS: ${TREE_AUDIT_MIN_INTERVAL_SECONDS:-300}",
		"TREE_AUDIT_MAX_RUNS_PER_SESSION: ${TREE_AUDIT_MAX_RUNS_PER_SESSION:-20}",
		"TREE_AUDIT_MAX_RUNS_PER_HOUR: ${TREE_AUDIT_MAX_RUNS_PER_HOUR:-12}",
		"TREE_AUDIT_HIGH_SEVERITY_MIN_INTERVAL_SECONDS: ${TREE_AUDIT_HIGH_SEVERITY_MIN_INTERVAL_SECONDS:-60}",
		"TREE_AUDIT_HIGH_SEVERITY_MAX_RUNS_PER_HOUR: ${TREE_AUDIT_HIGH_SEVERITY_MAX_RUNS_PER_HOUR:-4}",
		"TREE_AUDIT_UNAPPLIED_WARNING_THRESHOLD: ${TREE_AUDIT_UNAPPLIED_WARNING_THRESHOLD:-3}",
	}
	for _, item := range want {
		if !strings.Contains(compose, item) {
			t.Errorf("compose api environment is missing %q", item)
		}
	}
}

func TestComposePassesAnalysisAndWatchdogConfigurationToAPI(t *testing.T) {
	path := filepath.Join("..", "..", "compose.yaml")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	compose := string(content)
	want := []string{
		"DECISCOPE_TRANSCRIPT_ONLY: ${DECISCOPE_TRANSCRIPT_ONLY:-false}",
		"AI_FINALIZATION_WAIT_TIMEOUT_SECONDS: ${AI_FINALIZATION_WAIT_TIMEOUT_SECONDS:-10}",
		"AI_FINALIZATION_QUIET_PERIOD_MILLISECONDS: ${AI_FINALIZATION_QUIET_PERIOD_MILLISECONDS:-750}",
		"AI_FINAL_FLUSH_MAX_ATTEMPTS: ${AI_FINAL_FLUSH_MAX_ATTEMPTS:-3}",
		"AI_ANALYSIS_DEBUG_DROPPED_NODES: ${AI_ANALYSIS_DEBUG_DROPPED_NODES:-false}",
		"AI_TREE_AGENDA_ASSIGNMENT_THRESHOLD: ${AI_TREE_AGENDA_ASSIGNMENT_THRESHOLD:-0.55}",
		"AI_TREE_TOPIC_PROMOTION_MIN_ITEMS: ${AI_TREE_TOPIC_PROMOTION_MIN_ITEMS:-2}",
		"AI_TREE_TOPIC_PROMOTION_MIN_ROUNDS: ${AI_TREE_TOPIC_PROMOTION_MIN_ROUNDS:-2}",
		"AI_TREE_MAX_DYNAMIC_TOPICS: ${AI_TREE_MAX_DYNAMIC_TOPICS:-6}",
		"DECISCOPE_SESSION_WATCHDOG_ENABLED: ${DECISCOPE_SESSION_WATCHDOG_ENABLED:-true}",
		"DECISCOPE_SESSION_WATCHDOG_INTERVAL_SECONDS: ${DECISCOPE_SESSION_WATCHDOG_INTERVAL_SECONDS:-15}",
		"DECISCOPE_SESSION_BOT_LOST_AFTER_SECONDS: ${DECISCOPE_SESSION_BOT_LOST_AFTER_SECONDS:-60}",
		"DECISCOPE_SESSION_BOT_END_AFTER_SECONDS: ${DECISCOPE_SESSION_BOT_END_AFTER_SECONDS:-180}",
		"DECISCOPE_TRANSCRIPT_DELAYED_AFTER_SECONDS: ${DECISCOPE_TRANSCRIPT_DELAYED_AFTER_SECONDS:-30}",
		"DECISCOPE_TRANSCRIPT_STALLED_AFTER_SECONDS: ${DECISCOPE_TRANSCRIPT_STALLED_AFTER_SECONDS:-60}",
		"DECISCOPE_AUDIO_SILENCE_AFTER_SECONDS: ${DECISCOPE_AUDIO_SILENCE_AFTER_SECONDS:-30}",
		"DECISCOPE_AUDIO_STALLED_AFTER_SECONDS: ${DECISCOPE_AUDIO_STALLED_AFTER_SECONDS:-60}",
		"DECISCOPE_SPEECH_STALLED_AFTER_SECONDS: ${DECISCOPE_SPEECH_STALLED_AFTER_SECONDS:-60}",
	}
	for _, item := range want {
		if !strings.Contains(compose, item) {
			t.Errorf("compose api environment is missing %q", item)
		}
	}
}

// クライアント診断ログはホスト側から {sessionId}.jsonl を直接読めることが要件のため、
// 保存先の環境変数と bind mount が両方揃っていることを確認する。
func TestComposeMountsClientDiagnosticsLogDirectory(t *testing.T) {
	path := filepath.Join("..", "..", "compose.yaml")
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	compose := string(content)
	want := []string{
		"DECISCOPE_CLIENT_DIAGNOSTICS_ENABLED: ${DECISCOPE_CLIENT_DIAGNOSTICS_ENABLED:-true}",
		"DECISCOPE_CLIENT_DIAGNOSTICS_DIR: ${DECISCOPE_CLIENT_DIAGNOSTICS_DIR:-/app/logs/client-diagnostics}",
		"DECISCOPE_CLIENT_DIAGNOSTICS_MAX_FILE_MB: ${DECISCOPE_CLIENT_DIAGNOSTICS_MAX_FILE_MB:-10}",
		"DECISCOPE_CLIENT_DIAGNOSTICS_RETENTION_DAYS: ${DECISCOPE_CLIENT_DIAGNOSTICS_RETENTION_DAYS:-7}",
		"- ./logs/client-diagnostics:/app/logs/client-diagnostics",
	}
	for _, item := range want {
		if !strings.Contains(compose, item) {
			t.Errorf("compose api service is missing %q", item)
		}
	}
}
